# For Atom Feed
author: BigPipe Team
title: BigPipe
description: A radical new node.js framework

pygments: true
exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

markdown: rdiscount

sass:
  style: :compressed
version: 0.9.2
